### ISSUE TITLE
The seed of this code?

### ISSUE THREAD

**Issue by hhxxttxsh** [tsenghungchen/show-adapt-and-tell#1]
Hi, thank you for sharing your code.
I am wondering how you set up the seed for this code so that we can reproduce your results.

**Comment by tsenghungchen** [comment]
Hi, if you are referring to the seed of the weight initialization, it's okay to initialize with a different seed.
It should make little difference in the final performance.

**Comment by hhxxttxsh** [comment]
Hi, how little the difference could be? 

Thanks,
Ruomei

**Comment by hhxxttxsh** [comment]
Hi, could you please let me know why you choose tensorflow 0.12.1 rather than the latest version? In order to reproduce your results in the paper, do I have to use this exact version?

Thanks!

**Comment by tsenghungchen** [comment]
If you're using the version > 0.12.1, you might need to rename some functions to the newer ones.
As long as you can run the code, there's nothing to worry about!
