### ISSUE TITLE
Parameter "data" is not defined

### ISSUE THREAD

**Issue by nku428** [tsenghungchen/show-adapt-and-tell#4]
https://github.com/tsenghungchen/show-adapt-and-tell/blob/e97fd47be518ee41ade36472dc233042024c9c69/data-prepro/CUB200_preprocess/CUB_preprocess_token.py#L77

**Comment by tsenghungchen** [comment]
You can load the file `K_cleaned_words.npz` instead. 
Please see the below updated code for details.
https://github.com/tsenghungchen/show-adapt-and-tell/blob/master/data-prepro/CUB200_preprocess/CUB_preprocess_token.py#L76
