### ISSUE TITLE
from coco_spice.pycocoevalcap.eval import COCOEvalCap

### ISSUE THREAD

**Issue by lkeab** [tsenghungchen/show-adapt-and-tell#7]
how to solve this error: "ImportError: No module named coco_spice.pycocoevalcap.eval"  in pretrain_G.py
which takes three parameters like "COCOEvalCap(test_annotation, meteor_pd, meteor_id)"  but the implementation in coco only contains two.

**Comment by tsenghungchen** [comment]
You're right, this part of the code is modified from the original one.
You can change the following line 
https://github.com/peteanderson80/coco-caption/blob/18cb4658df39e6abe2fc4f68ce367a7d8de00e59/pycocoevalcap/eval.py#L16
into 
```
self.params = {'image_id': ImgIds} 
```
and add "ImgIds" as a new parameter in "COCOEvalCap".
Modification in function "evaluate" is required, too.

**Comment by lkeab** [comment]
Thanks for your reply and help . Can you please describe more about the modification in function "evaluate"?

**Comment by Pony-Kelei** [comment]
I tried simply change the line 16 doesn't work and modify "evaluate" function by myself but it doesn't work.

**Comment by lkeab** [comment]
I tried simply modify the "evaluate" function and L16 but it doesn't work.

**Comment by tsenghungchen** [comment]
Here is the partial code of the "evaluate" function. Please take a look.
```    
def evaluate(self, verbose=False):
        imgIds = self.params['image_id']
        # imgIds = self.coco.getImgIds()
        gts = {}
        res = {}
        for imgId in imgIds:
            if "_" in imgId:
                gts[imgId] = self.coco[imgId.split("_")[0]]
            else:
                gts[imgId] = self.coco[imgId]
            res[imgId] = self.cocoRes[imgId]
#            gts[imgId] = self.coco.imgToAnns[imgId]
#            res[imgId] = self.cocoRes.imgToAnns[imgId]
```

**Comment by lkeab** [comment]
Thanks for your patient reply~
