### ISSUE TITLE
Why two critics have different text encoders?

### ISSUE THREAD

**Issue by cookielee77** [tsenghungchen/show-adapt-and-tell#8]
Why does domain critic use the CNN as the text encoder, but multi-modal critic use the LSTM as the text encoder? 

Any reason for this setting? Is it possible to use the CNN as the text encoder for both critics design? 

Thanks!

**Comment by tsenghungchen** [comment]
Please take a look at Sec. 3 in the [Supp.](https://tsenghungchen.github.io/show_adapt_tell/supp/show-adapt-tell-supp.pdf) material.
